#!/bin/sh

#
# Run the 'tibero' command of the Tibero service container.
#
# environment variables:
#   Check for the 'get_env.sh' file to get which environment variables are available.
#

# external envs
export ENV_FILE    # which env file to read

# path envs
BIN_ORIG="$(readlink -f "${0}")"
ROOT_DIR="$(dirname "${BIN_ORIG?:binary path error!}")"

# load common env
. "${ROOT_DIR}/get_env.sh"


# run tibero command on the running container
${OCI_CMD} exec -it "${TB_CNT_NAME}" tibero "${@}"
